// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/code/lexico/AnalizadorLexico.flex

package code.lexico;

import compilerTools.Token;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;


@SuppressWarnings("fallthrough")
public class AnalizadorLexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\2\u1f00\1\u2100\4\u1f00\1\u2200"+
    "\1\u2300\1\u2400\1\u1f00\1\u2500\1\u2600\1\u2700\1\u1f00\31\u0100"+
    "\1\u2800\121\u0100\1\u2900\4\u0100\1\u2a00\1\u0100\1\u2b00\1\u2c00"+
    "\1\u2d00\1\u2e00\1\u2f00\1\u3000\53\u0100\1\u3100\10\u3200\31\u1f00"+
    "\1\u0100\1\u3300\1\u3400\1\u0100\1\u3500\1\u3600\1\u3700\1\u3800"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u0100\1\u3e00\1\u3f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00"+
    "\1\u5000\1\u5100\1\u1f00\1\u5200\1\u5300\1\u5400\1\u5500\3\u0100"+
    "\1\u5600\1\u5700\1\u5800\12\u1f00\4\u0100\1\u5900\17\u1f00\2\u0100"+
    "\1\u5a00\41\u1f00\2\u0100\1\u5b00\1\u5c00\2\u1f00\1\u5d00\1\u5e00"+
    "\27\u0100\1\u5f00\2\u0100\1\u6000\45\u1f00\1\u0100\1\u6100\1\u6200"+
    "\11\u1f00\1\u6300\25\u1f00\1\u6400\1\u6500\1\u6600\1\u6700\1\u6800"+
    "\1\u6900\11\u1f00\1\u6a00\1\u6b00\5\u1f00\1\u6c00\1\u6d00\2\u1f00"+
    "\1\u6e00\1\u6f00\1\u7000\2\u1f00\1\u7100\16\u1f00\246\u0100\1\u7200"+
    "\20\u0100\1\u7300\1\u7400\25\u0100\1\u7500\34\u0100\1\u7600\14\u1f00"+
    "\2\u0100\1\u7700\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\12\24"+
    "\1\25\1\26\1\27\1\30\1\31\2\0\32\32\1\33"+
    "\1\34\1\35\1\0\1\32\1\0\1\36\1\32\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\2\32\1\46"+
    "\1\47\1\50\1\51\1\52\1\32\1\53\1\54\1\55"+
    "\1\56\1\57\1\32\1\60\1\61\1\32\1\62\1\0"+
    "\1\63\7\0\1\3\44\0\1\32\7\0\2\64\1\0"+
    "\1\32\3\0\1\64\1\32\1\0\3\64\1\0\27\32"+
    "\1\0\37\32\1\0\u01ca\32\4\0\14\32\16\0\5\32"+
    "\7\0\1\32\1\0\1\32\201\0\5\32\1\0\2\32"+
    "\2\0\4\32\1\0\1\32\6\0\1\32\1\0\3\32"+
    "\1\0\1\32\1\0\24\32\1\0\123\32\1\0\213\32"+
    "\10\0\246\32\1\0\46\32\2\0\1\32\6\0\51\32"+
    "\107\0\33\32\4\0\4\32\55\0\53\32\25\0\12\64"+
    "\4\0\2\32\1\0\143\32\1\0\1\32\17\0\2\32"+
    "\7\0\2\32\12\64\3\32\2\0\1\32\20\0\1\32"+
    "\1\0\36\32\35\0\131\32\13\0\1\32\16\0\12\64"+
    "\41\32\11\0\2\32\4\0\1\32\5\0\26\32\4\0"+
    "\1\32\11\0\1\32\3\0\1\32\27\0\31\32\7\0"+
    "\13\32\65\0\25\32\1\0\10\32\106\0\66\32\3\0"+
    "\1\32\22\0\1\32\7\0\12\32\4\0\12\64\1\0"+
    "\20\32\4\0\10\32\2\0\2\32\2\0\26\32\1\0"+
    "\7\32\1\0\1\32\3\0\4\32\3\0\1\32\20\0"+
    "\1\32\15\0\2\32\1\0\3\32\4\0\12\64\2\32"+
    "\2\0\6\64\2\0\1\32\10\0\6\32\4\0\2\32"+
    "\2\0\26\32\1\0\7\32\1\0\2\32\1\0\2\32"+
    "\1\0\2\32\37\0\4\32\1\0\1\32\7\0\12\64"+
    "\2\0\3\32\20\0\11\32\1\0\3\32\1\0\26\32"+
    "\1\0\7\32\1\0\2\32\1\0\5\32\3\0\1\32"+
    "\22\0\1\32\17\0\2\32\4\0\12\64\11\0\1\32"+
    "\13\0\10\32\2\0\2\32\2\0\26\32\1\0\7\32"+
    "\1\0\2\32\1\0\5\32\3\0\1\32\36\0\2\32"+
    "\1\0\3\32\4\0\12\64\1\0\1\32\6\64\13\0"+
    "\1\32\1\0\6\32\3\0\3\32\1\0\4\32\3\0"+
    "\2\32\1\0\1\32\1\0\2\32\3\0\2\32\3\0"+
    "\3\32\3\0\14\32\26\0\1\32\25\0\15\64\22\0"+
    "\10\32\1\0\3\32\1\0\27\32\1\0\20\32\3\0"+
    "\1\32\32\0\3\32\5\0\2\32\4\0\12\64\10\0"+
    "\7\64\1\0\1\32\4\0\10\32\1\0\3\32\1\0"+
    "\27\32\1\0\12\32\1\0\5\32\3\0\1\32\40\0"+
    "\1\32\1\0\2\32\4\0\12\64\1\0\2\32\22\0"+
    "\10\32\1\0\3\32\1\0\51\32\2\0\1\32\20\0"+
    "\1\32\5\0\3\32\1\0\7\64\3\32\4\0\23\64"+
    "\1\0\6\32\5\0\22\32\3\0\30\32\1\0\11\32"+
    "\1\0\1\32\2\0\7\32\37\0\12\64\21\0\60\32"+
    "\1\0\2\32\14\0\7\32\11\0\12\64\47\0\2\32"+
    "\1\0\1\32\1\0\5\32\1\0\30\32\1\0\1\32"+
    "\1\0\12\32\1\0\2\32\11\0\1\32\2\0\5\32"+
    "\1\0\1\32\11\0\12\64\2\0\4\32\40\0\1\32"+
    "\37\0\24\64\14\0\10\32\1\0\44\32\33\0\5\32"+
    "\163\0\53\32\24\0\1\32\12\64\6\0\6\32\4\0"+
    "\4\32\3\0\1\32\3\0\2\32\7\0\3\32\4\0"+
    "\15\32\14\0\1\32\1\0\12\64\6\0\46\32\1\0"+
    "\1\32\5\0\1\32\2\0\53\32\1\0\115\32\1\0"+
    "\4\32\2\0\7\32\1\0\1\32\1\0\4\32\2\0"+
    "\51\32\1\0\4\32\2\0\41\32\1\0\4\32\2\0"+
    "\7\32\1\0\1\32\1\0\4\32\2\0\17\32\1\0"+
    "\71\32\1\0\4\32\2\0\103\32\16\0\24\64\3\0"+
    "\20\32\20\0\126\32\2\0\6\32\3\0\u016c\32\2\0"+
    "\21\32\1\0\32\32\5\0\113\32\3\0\3\64\10\32"+
    "\7\0\15\32\1\0\4\32\16\0\22\32\16\0\22\32"+
    "\16\0\15\32\1\0\3\32\17\0\64\32\43\0\1\32"+
    "\4\0\1\32\3\0\12\64\6\0\12\64\26\0\12\64"+
    "\6\0\131\32\7\0\5\32\2\0\42\32\1\0\1\32"+
    "\5\0\106\32\12\0\37\32\47\0\12\64\36\32\2\0"+
    "\5\32\13\0\54\32\4\0\32\32\6\0\13\64\45\0"+
    "\27\32\11\0\65\32\53\0\12\64\6\0\12\64\15\0"+
    "\1\32\135\0\57\32\21\0\7\32\4\0\12\64\51\0"+
    "\36\32\15\0\2\32\12\64\54\32\32\0\44\32\34\0"+
    "\12\64\3\0\3\32\12\64\44\32\2\0\11\32\7\0"+
    "\53\32\2\0\3\32\51\0\4\32\1\0\6\32\1\0"+
    "\2\32\3\0\1\32\5\0\300\32\100\0\26\32\2\0"+
    "\6\32\2\0\46\32\2\0\6\32\2\0\10\32\1\0"+
    "\1\32\1\0\1\32\1\0\1\32\1\0\37\32\2\0"+
    "\65\32\1\0\7\32\1\0\1\32\3\0\3\32\1\0"+
    "\7\32\3\0\4\32\2\0\6\32\4\0\15\32\5\0"+
    "\3\32\1\0\7\32\53\0\2\3\106\0\1\64\1\32"+
    "\2\0\6\64\5\0\1\32\12\64\6\0\15\32\145\0"+
    "\1\32\4\0\1\32\2\0\12\32\1\0\1\32\3\0"+
    "\5\32\6\0\1\32\1\0\1\32\1\0\1\32\1\0"+
    "\4\32\1\0\13\32\2\0\4\32\5\0\5\32\4\0"+
    "\1\32\1\0\63\64\2\32\5\64\u01d6\0\74\64\116\0"+
    "\26\64\166\0\36\64\154\0\57\32\1\0\57\32\1\0"+
    "\205\32\6\0\4\32\3\0\2\32\11\0\1\64\2\0"+
    "\46\32\1\0\1\32\5\0\1\32\2\0\70\32\7\0"+
    "\1\32\20\0\27\32\11\0\7\32\1\0\7\32\1\0"+
    "\7\32\1\0\7\32\1\0\7\32\1\0\7\32\1\0"+
    "\7\32\1\0\7\32\120\0\1\32\325\0\2\32\1\64"+
    "\31\0\11\64\7\0\5\32\2\0\3\64\2\32\4\0"+
    "\126\32\6\0\3\32\1\0\132\32\1\0\4\32\5\0"+
    "\53\32\1\0\136\32\3\0\4\64\12\0\33\32\65\0"+
    "\20\32\40\0\12\64\36\0\10\64\1\0\17\64\40\0"+
    "\12\64\47\0\17\64\100\0\266\32\112\0\360\32\20\0"+
    "\215\32\103\0\56\32\2\0\15\32\3\0\20\32\12\64"+
    "\2\32\24\0\57\32\20\0\37\32\2\0\106\32\12\64"+
    "\47\0\11\32\2\0\147\32\2\0\65\32\2\0\5\32"+
    "\60\0\13\32\1\0\3\32\1\0\4\32\1\0\27\32"+
    "\15\0\6\64\12\0\64\32\16\0\62\32\34\0\12\64"+
    "\30\0\6\32\3\0\1\32\1\0\2\32\1\0\12\64"+
    "\34\32\12\0\27\32\31\0\35\32\7\0\57\32\34\0"+
    "\1\32\12\64\6\0\5\32\1\0\12\32\12\64\5\32"+
    "\1\0\51\32\27\0\3\32\1\0\10\32\4\0\12\64"+
    "\6\0\27\32\3\0\1\32\3\0\62\32\1\0\1\32"+
    "\3\0\2\32\2\0\5\32\2\0\1\32\1\0\1\32"+
    "\30\0\3\32\2\0\13\32\7\0\3\32\14\0\6\32"+
    "\2\0\6\32\2\0\6\32\11\0\7\32\1\0\7\32"+
    "\1\0\53\32\1\0\14\32\10\0\163\32\15\0\12\64"+
    "\6\0\244\32\14\0\27\32\4\0\61\32\4\0\u0100\3"+
    "\156\32\2\0\152\32\46\0\7\32\14\0\5\32\5\0"+
    "\1\32\1\0\12\32\1\0\15\32\1\0\5\32\1\0"+
    "\1\32\1\0\2\32\1\0\2\32\1\0\154\32\41\0"+
    "\153\32\22\0\100\32\2\0\66\32\50\0\14\32\164\0"+
    "\5\32\1\0\207\32\23\0\12\64\7\0\32\32\6\0"+
    "\32\32\13\0\131\32\3\0\6\32\2\0\6\32\2\0"+
    "\6\32\2\0\3\32\43\0\14\32\1\0\32\32\1\0"+
    "\23\32\1\0\2\32\1\0\17\32\2\0\16\32\42\0"+
    "\173\32\14\0\55\64\14\0\71\64\21\0\2\64\364\0"+
    "\35\32\3\0\61\32\20\0\33\64\4\0\40\32\4\64"+
    "\11\0\24\32\1\64\10\32\1\64\5\0\46\32\12\0"+
    "\36\32\2\0\44\32\4\0\10\32\1\0\5\64\52\0"+
    "\236\32\2\0\12\64\6\0\44\32\4\0\44\32\4\0"+
    "\50\32\10\0\64\32\234\0\67\32\11\0\26\32\12\0"+
    "\10\32\230\0\6\32\2\0\1\32\1\0\54\32\1\0"+
    "\2\32\3\0\1\32\2\0\27\32\2\0\10\64\27\32"+
    "\2\0\7\64\37\32\10\0\11\64\60\0\23\32\1\0"+
    "\2\32\5\0\5\64\26\32\6\64\4\0\32\32\106\0"+
    "\70\32\4\0\2\64\2\32\20\64\2\0\56\64\1\32"+
    "\17\0\4\32\1\0\3\32\1\0\35\32\12\0\11\64"+
    "\27\0\35\32\2\64\1\0\35\32\3\64\40\0\10\32"+
    "\1\0\34\32\6\0\5\64\20\0\66\32\12\0\26\32"+
    "\2\0\10\64\23\32\5\0\10\64\22\32\27\0\7\64"+
    "\120\0\111\32\67\0\63\32\15\0\63\32\7\0\6\64"+
    "\44\32\14\0\12\64\u0126\0\37\64\201\0\35\32\12\64"+
    "\1\32\10\0\26\32\13\0\4\64\213\0\27\32\14\0"+
    "\65\32\32\0\36\64\23\0\55\32\40\0\31\32\7\0"+
    "\12\64\11\0\44\32\17\0\12\64\4\0\1\32\13\0"+
    "\43\32\3\0\1\32\14\0\60\32\16\0\4\32\13\0"+
    "\12\64\1\32\1\0\1\32\4\0\24\64\13\0\22\32"+
    "\1\0\31\32\124\0\7\32\1\0\1\32\1\0\4\32"+
    "\1\0\17\32\1\0\12\32\7\0\57\32\21\0\12\64"+
    "\13\0\10\32\2\0\2\32\2\0\26\32\1\0\7\32"+
    "\1\0\2\32\1\0\5\32\3\0\1\32\22\0\1\32"+
    "\14\0\5\32\236\0\65\32\22\0\4\32\5\0\12\64"+
    "\5\0\1\32\40\0\60\32\24\0\2\32\1\0\1\32"+
    "\10\0\12\64\246\0\57\32\51\0\4\32\44\0\60\32"+
    "\24\0\1\32\13\0\12\64\46\0\53\32\15\0\1\32"+
    "\7\0\12\64\66\0\33\32\25\0\14\64\304\0\54\32"+
    "\164\0\100\32\23\64\14\0\1\32\240\0\10\32\2\0"+
    "\47\32\20\0\1\32\1\0\1\32\34\0\1\32\12\0"+
    "\50\32\7\0\1\32\25\0\1\32\13\0\56\32\23\0"+
    "\1\32\42\0\71\32\7\0\11\32\1\0\45\32\21\0"+
    "\1\32\17\0\35\64\5\0\36\32\160\0\7\32\1\0"+
    "\2\32\1\0\46\32\25\0\1\32\11\0\12\64\6\0"+
    "\6\32\1\0\2\32\1\0\40\32\16\0\1\32\7\0"+
    "\12\64\u0136\0\23\32\315\0\25\64\53\0\232\32\146\0"+
    "\157\64\21\0\304\32\274\0\57\32\321\0\107\32\271\0"+
    "\71\32\7\0\37\32\1\0\12\64\146\0\36\32\22\0"+
    "\60\32\20\0\4\32\14\0\12\64\1\0\7\64\1\0"+
    "\25\32\5\0\23\32\260\0\100\32\27\64\151\0\113\32"+
    "\5\0\1\32\102\0\15\32\100\0\2\32\1\0\1\32"+
    "\34\0\370\32\10\0\363\32\15\0\37\32\61\0\3\32"+
    "\21\0\4\32\10\0\u018c\32\4\0\153\32\5\0\15\32"+
    "\3\0\11\32\7\0\12\32\u0146\0\24\64\154\0\31\64"+
    "\207\0\125\32\1\0\107\32\1\0\2\32\2\0\1\32"+
    "\2\0\2\32\2\0\4\32\1\0\14\32\1\0\1\32"+
    "\1\0\7\32\1\0\101\32\1\0\4\32\2\0\10\32"+
    "\1\0\7\32\1\0\34\32\1\0\4\32\1\0\5\32"+
    "\1\0\1\32\3\0\7\32\1\0\u0154\32\2\0\31\32"+
    "\1\0\31\32\1\0\37\32\1\0\31\32\1\0\37\32"+
    "\1\0\31\32\1\0\37\32\1\0\31\32\1\0\37\32"+
    "\1\0\31\32\1\0\10\32\2\0\62\64\55\32\12\0"+
    "\7\32\2\0\12\64\4\0\1\32\u0171\0\54\32\4\0"+
    "\12\64\6\0\305\32\2\0\11\64\60\0\104\32\7\0"+
    "\1\32\4\0\12\64\u0117\0\73\64\1\0\3\64\1\0"+
    "\4\64\114\0\55\64\1\0\17\64\302\0\4\32\1\0"+
    "\33\32\1\0\2\32\1\0\1\32\2\0\1\32\1\0"+
    "\12\32\1\0\4\32\1\0\1\32\1\0\1\32\6\0"+
    "\1\32\4\0\1\32\1\0\1\32\1\0\1\32\1\0"+
    "\3\32\1\0\2\32\1\0\1\32\2\0\1\32\1\0"+
    "\1\32\1\0\1\32\1\0\1\32\1\0\1\32\1\0"+
    "\2\32\1\0\1\32\2\0\4\32\1\0\7\32\1\0"+
    "\4\32\1\0\4\32\1\0\1\32\1\0\12\32\1\0"+
    "\21\32\5\0\3\32\1\0\5\32\1\0\21\32\104\0"+
    "\15\64\363\0\327\32\51\0\65\32\13\0\336\32\2\0"+
    "\u0182\32\16\0\u0131\32\37\0\36\32\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[30720];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\2\1\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\14\21\1\24"+
    "\1\25\1\0\1\26\1\0\1\27\1\30\2\0\1\31"+
    "\1\0\1\2\4\0\1\32\1\0\1\33\1\34\1\35"+
    "\1\36\1\37\20\21\1\40\3\21\1\41\1\42\1\2"+
    "\1\0\1\43\1\44\1\45\1\46\1\47\1\50\11\21"+
    "\1\51\13\21\1\52\1\0\1\53\12\21\1\54\1\55"+
    "\4\21\1\56\3\21\1\57\1\60\2\21\1\61\1\21"+
    "\1\62\1\63\4\21\1\64\1\65\1\66\1\67\2\21"+
    "\1\70\1\71\1\72\1\21\1\73\1\74\1\75\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\65\0\152\0\237\0\324\0\u0109\0\u013e"+
    "\0\65\0\65\0\u0173\0\u01a8\0\65\0\u01dd\0\65\0\u0212"+
    "\0\u0247\0\u027c\0\65\0\u02b1\0\u02e6\0\u031b\0\65\0\65"+
    "\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3"+
    "\0\u04f8\0\u052d\0\u0562\0\u0597\0\65\0\65\0\237\0\65"+
    "\0\u05cc\0\65\0\65\0\u0601\0\u0636\0\65\0\u066b\0\u06a0"+
    "\0\u06d5\0\u070a\0\u073f\0\u0774\0\65\0\u07a9\0\65\0\65"+
    "\0\65\0\65\0\65\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2"+
    "\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a"+
    "\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\65"+
    "\0\65\0\u0c02\0\u0c37\0\65\0\65\0\65\0\65\0\u07a9"+
    "\0\u031b\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa"+
    "\0\u0ddf\0\u0e14\0\u031b\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d"+
    "\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b\0\u031b\0\u1090"+
    "\0\u031b\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203"+
    "\0\u1238\0\u126d\0\u12a2\0\u031b\0\u031b\0\u12d7\0\u130c\0\u1341"+
    "\0\u1376\0\u031b\0\u13ab\0\u13e0\0\u1415\0\u031b\0\u031b\0\u144a"+
    "\0\u147f\0\u031b\0\u14b4\0\u031b\0\u031b\0\u14e9\0\u151e\0\u1553"+
    "\0\u1588\0\u031b\0\u031b\0\u031b\0\u031b\0\u15bd\0\u15f2\0\u031b"+
    "\0\u031b\0\u031b\0\u1627\0\u031b\0\u031b\0\u031b\0\u031b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\2\1\5\1\2"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\2"+
    "\1\25\1\26\1\27\1\2\1\30\1\26\1\31\1\32"+
    "\1\33\1\34\1\26\1\35\1\36\1\37\1\40\3\26"+
    "\1\41\1\42\1\43\1\26\1\44\2\26\1\45\1\46"+
    "\1\2\67\0\1\3\62\0\2\47\1\0\2\47\1\0"+
    "\1\47\1\50\24\47\1\51\30\47\11\0\1\52\72\0"+
    "\1\53\45\0\2\54\1\0\2\54\1\0\5\54\1\0"+
    "\20\54\1\55\30\54\16\0\1\56\65\0\1\57\55\0"+
    "\1\60\10\0\1\61\26\0\1\62\1\63\7\0\1\64"+
    "\26\0\1\65\63\0\1\66\1\0\1\21\46\0\1\67"+
    "\16\0\1\70\2\0\1\71\64\0\1\72\64\0\1\73"+
    "\60\0\1\26\5\0\1\26\3\0\24\26\2\0\1\26"+
    "\24\0\1\26\5\0\1\26\3\0\1\74\6\26\1\75"+
    "\3\26\1\76\10\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\3\26\1\77\3\26\1\100\14\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\12\26\1\101"+
    "\11\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\1\102\6\26\1\103\14\26\2\0\1\26\24\0\1\26"+
    "\5\0\1\26\3\0\1\104\23\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\12\26\1\105\3\26\1\106"+
    "\5\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\3\26\1\107\7\26\1\110\10\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\13\26\1\111\10\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\3\26\1\112"+
    "\7\26\1\113\10\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\7\26\1\114\10\26\1\115\3\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\3\26\1\116"+
    "\20\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\1\117\23\26\2\0\1\26\2\47\4\0\57\47\13\0"+
    "\1\120\51\0\2\54\4\0\57\54\31\0\1\121\33\0"+
    "\2\122\1\0\2\122\1\0\25\122\1\123\31\122\27\0"+
    "\1\124\56\0\1\125\64\0\1\126\64\0\1\127\67\0"+
    "\1\130\64\0\1\26\5\0\1\26\3\0\15\26\1\131"+
    "\1\132\5\26\2\0\1\26\24\0\1\26\5\0\1\26"+
    "\3\0\3\26\1\133\20\26\2\0\1\26\24\0\1\26"+
    "\5\0\1\26\3\0\12\26\1\134\2\26\1\135\6\26"+
    "\2\0\1\26\24\0\1\26\5\0\1\26\3\0\1\26"+
    "\1\136\2\26\1\137\17\26\2\0\1\26\24\0\1\26"+
    "\5\0\1\26\3\0\3\26\1\140\20\26\2\0\1\26"+
    "\24\0\1\26\5\0\1\26\3\0\17\26\1\141\4\26"+
    "\2\0\1\26\24\0\1\26\5\0\1\26\3\0\10\26"+
    "\1\142\13\26\2\0\1\26\24\0\1\26\5\0\1\26"+
    "\3\0\12\26\1\143\11\26\2\0\1\26\24\0\1\26"+
    "\5\0\1\26\3\0\16\26\1\144\5\26\2\0\1\26"+
    "\24\0\1\26\5\0\1\26\3\0\7\26\1\145\14\26"+
    "\2\0\1\26\24\0\1\26\5\0\1\26\3\0\1\146"+
    "\23\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\3\26\1\147\20\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\5\26\1\150\16\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\16\26\1\151\5\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\14\26\1\152"+
    "\7\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\11\26\1\153\12\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\12\26\1\154\11\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\7\26\1\155\14\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\22\26\1\156"+
    "\1\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\15\26\1\157\6\26\2\0\1\26\2\122\1\0\2\122"+
    "\1\0\57\122\35\123\1\160\27\123\24\0\1\26\5\0"+
    "\1\26\3\0\13\26\1\161\10\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\15\26\1\162\6\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\16\26\1\163"+
    "\5\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\17\26\1\164\4\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\7\26\1\165\14\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\3\26\1\166\20\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\5\26\1\167"+
    "\16\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\3\26\1\170\20\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\16\26\1\171\5\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\17\26\1\172\4\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\1\26\1\173"+
    "\22\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\1\26\1\174\22\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\15\26\1\175\6\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\7\26\1\176\14\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\17\26\1\177"+
    "\4\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\7\26\1\200\14\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\14\26\1\201\7\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\13\26\1\202\10\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\1\26\1\203"+
    "\22\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\17\26\1\204\4\26\2\0\1\26\10\123\1\3\54\123"+
    "\24\0\1\26\5\0\1\26\3\0\17\26\1\205\4\26"+
    "\2\0\1\26\24\0\1\26\5\0\1\26\3\0\17\26"+
    "\1\206\4\26\2\0\1\26\24\0\1\26\5\0\1\26"+
    "\3\0\13\26\1\207\10\26\2\0\1\26\24\0\1\26"+
    "\5\0\1\26\3\0\11\26\1\210\12\26\2\0\1\26"+
    "\24\0\1\26\5\0\1\26\3\0\1\26\1\211\22\26"+
    "\2\0\1\26\24\0\1\26\5\0\1\26\3\0\13\26"+
    "\1\212\10\26\2\0\1\26\24\0\1\26\5\0\1\26"+
    "\3\0\15\26\1\213\6\26\2\0\1\26\24\0\1\26"+
    "\5\0\1\26\3\0\13\26\1\214\10\26\2\0\1\26"+
    "\24\0\1\26\5\0\1\26\3\0\1\215\23\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\7\26\1\216"+
    "\14\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\1\26\1\217\22\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\15\26\1\220\6\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\17\26\1\221\4\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\3\26\1\222"+
    "\20\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\6\26\1\223\15\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\13\26\1\224\10\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\13\26\1\225\10\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\1\226\23\26"+
    "\2\0\1\26\24\0\1\26\5\0\1\26\3\0\17\26"+
    "\1\227\4\26\2\0\1\26\24\0\1\26\5\0\1\26"+
    "\3\0\13\26\1\230\10\26\2\0\1\26\24\0\1\26"+
    "\5\0\1\26\3\0\13\26\1\231\10\26\2\0\1\26"+
    "\24\0\1\26\5\0\1\26\3\0\13\26\1\232\10\26"+
    "\2\0\1\26\24\0\1\26\5\0\1\26\3\0\1\233"+
    "\23\26\2\0\1\26\24\0\1\26\5\0\1\26\3\0"+
    "\3\26\1\234\20\26\2\0\1\26\24\0\1\26\5\0"+
    "\1\26\3\0\10\26\1\235\13\26\2\0\1\26\24\0"+
    "\1\26\5\0\1\26\3\0\13\26\1\236\10\26\2\0"+
    "\1\26\24\0\1\26\5\0\1\26\3\0\15\26\1\237"+
    "\6\26\2\0\1\26";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5724];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\2\11\2\1\1\11\1\1\1\11"+
    "\3\1\1\11\3\1\2\11\14\1\2\11\1\0\1\11"+
    "\1\0\2\11\2\0\1\11\1\0\1\1\4\0\1\11"+
    "\1\0\5\11\24\1\2\11\1\1\1\0\4\11\30\1"+
    "\1\0\57\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private Token token(String lexema, String componenteLexico, int line, int column)
   {
    return new Token(lexema, componenteLexico, line+1, column+1);
   }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
      //Seccion del Constructor  
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
          // fall through
          case 63: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 64: break;
          case 3:
            { return token(yytext(),"MODULO",yyline,yycolumn);
            }
          // fall through
          case 65: break;
          case 4:
            { return token(yytext(), "PAREN_IZQ", yyline, yycolumn);
            }
          // fall through
          case 66: break;
          case 5:
            { return token(yytext(), "PAREN_DER", yyline, yycolumn);
            }
          // fall through
          case 67: break;
          case 6:
            { return token(yytext(),"MULTIPLICACION",yyline,yycolumn);
            }
          // fall through
          case 68: break;
          case 7:
            { return token(yytext(),"SUMA",yyline,yycolumn);
            }
          // fall through
          case 69: break;
          case 8:
            { return token(yytext(), "COMA", yyline, yycolumn);
            }
          // fall through
          case 70: break;
          case 9:
            { return token(yytext(),"RESTA",yyline,yycolumn);
            }
          // fall through
          case 71: break;
          case 10:
            { return token(yytext(), "PUNTO", yyline, yycolumn);
            }
          // fall through
          case 72: break;
          case 11:
            { return token(yytext(),"DIVISION",yyline,yycolumn);
            }
          // fall through
          case 73: break;
          case 12:
            { return token(yytext(),"ENTERO",yyline,yycolumn);
            }
          // fall through
          case 74: break;
          case 13:
            { return token(yytext(), "DOS_PUNTOS", yyline, yycolumn);
            }
          // fall through
          case 75: break;
          case 14:
            { return token(yytext(), "PUNTO_COMA", yyline, yycolumn);
            }
          // fall through
          case 76: break;
          case 15:
            { return token(yytext(),"OP_MENOR",yyline,yycolumn);
            }
          // fall through
          case 77: break;
          case 16:
            { return token(yytext(),"OP_MAYOR",yyline,yycolumn);
            }
          // fall through
          case 78: break;
          case 17:
            { return token(yytext(),"IDENTIFICADOR",yyline,yycolumn);
            }
          // fall through
          case 79: break;
          case 18:
            { return token(yytext(),"CORCH_IZQ",yyline,yycolumn);
            }
          // fall through
          case 80: break;
          case 19:
            { return token(yytext(),"CORCH_DER",yyline,yycolumn);
            }
          // fall through
          case 81: break;
          case 20:
            { return token(yytext(), "LLAVE_IZQ", yyline, yycolumn);
            }
          // fall through
          case 82: break;
          case 21:
            { return token(yytext(), "LLAVE_DER", yyline, yycolumn);
            }
          // fall through
          case 83: break;
          case 22:
            { return token(yytext(),"CADENA",yyline,yycolumn);
            }
          // fall through
          case 84: break;
          case 23:
            { return token(yytext(),"OP_MOD_MOD",yyline,yycolumn);
            }
          // fall through
          case 85: break;
          case 24:
            { return token(yytext(),"CONCAT",yyline,yycolumn);
            }
          // fall through
          case 86: break;
          case 25:
            { return token(yytext(),"OP_MULT_MULTI",yyline,yycolumn);
            }
          // fall through
          case 87: break;
          case 26:
            { return token(yytext(),"OP_DIV_DIV",yyline,yycolumn);
            }
          // fall through
          case 88: break;
          case 27:
            { return token(yytext(),"OP_DIFERENTE",yyline,yycolumn);
            }
          // fall through
          case 89: break;
          case 28:
            { return token(yytext(),"OP_IGUAL_IGUAL",yyline,yycolumn);
            }
          // fall through
          case 90: break;
          case 29:
            { return token(yytext(),"ASIGNACION",yyline,yycolumn);
            }
          // fall through
          case 91: break;
          case 30:
            { return token(yytext(),"OP_MENOR_IGUAL",yyline,yycolumn);
            }
          // fall through
          case 92: break;
          case 31:
            { return token(yytext(),"OP_MAYOR_IGUAL",yyline,yycolumn);
            }
          // fall through
          case 93: break;
          case 32:
            { return token(yytext(),"SI",yyline,yycolumn);
            }
          // fall through
          case 94: break;
          case 33:
            { return token(yytext(),"CARACTER",yyline,yycolumn);
            }
          // fall through
          case 95: break;
          case 34:
            { return token(yytext(),"OP_INCREMENTO",yyline,yycolumn);
            }
          // fall through
          case 96: break;
          case 35:
            { return token(yytext(),"OP_DECREMENTO",yyline,yycolumn);
            }
          // fall through
          case 97: break;
          case 36:
            { return token(yytext(),"LOGICO_NOT",yyline,yycolumn);
            }
          // fall through
          case 98: break;
          case 37:
            { return token(yytext(),"LOGICO_OR",yyline,yycolumn);
            }
          // fall through
          case 99: break;
          case 38:
            { return token(yytext(),"LOGICO_AND",yyline,yycolumn);
            }
          // fall through
          case 100: break;
          case 39:
            { return token(yytext(),"FLOTANTE",yyline,yycolumn);
            }
          // fall through
          case 101: break;
          case 40:
            { return token(yytext(),"TIPO_CAR",yyline,yycolumn);
            }
          // fall through
          case 102: break;
          case 41:
            { return token(yytext(),"FIN",yyline,yycolumn);
            }
          // fall through
          case 103: break;
          case 42:
            { return token(yytext(),"VAR",yyline,yycolumn);
            }
          // fall through
          case 104: break;
          case 43:
            { return token(yytext(),"CASE",yyline,yycolumn);
            }
          // fall through
          case 105: break;
          case 44:
            { return token(yytext(),"FOR",yyline,yycolumn);
            }
          // fall through
          case 106: break;
          case 45:
            { return token(yytext(),"LEER",yyline,yycolumn);
            }
          // fall through
          case 107: break;
          case 46:
            { return token(yytext(),"SINO",yyline,yycolumn);
            }
          // fall through
          case 108: break;
          case 47:
            { return token(yytext(),"CONST",yyline,yycolumn);
            }
          // fall through
          case 109: break;
          case 48:
            { return token(yytext(),"TIPO_CORTO",yyline,yycolumn);
            }
          // fall through
          case 110: break;
          case 49:
            { return token(yytext(),"WHILE",yyline,yycolumn);
            }
          // fall through
          case 111: break;
          case 50:
            { return token(yytext(),"BOOLEAN_FALSE",yyline,yycolumn);
            }
          // fall through
          case 112: break;
          case 51:
            { return token(yytext(),"HASTA",yyline,yycolumn);
            }
          // fall through
          case 113: break;
          case 52:
            { return token(yytext(),"BREAK",yyline,yycolumn);
            }
          // fall through
          case 114: break;
          case 53:
            { return token(yytext(),"SWITCH",yyline,yycolumn);
            }
          // fall through
          case 115: break;
          case 54:
            { return token(yytext(),"TIPO_TEXTO",yyline,yycolumn);
            }
          // fall through
          case 116: break;
          case 55:
            { return token(yytext(),"BOOLEAN_TRUE",yyline,yycolumn);
            }
          // fall through
          case 117: break;
          case 56:
            { return token(yytext(),"TIPO_ENTERO",yyline,yycolumn);
            }
          // fall through
          case 118: break;
          case 57:
            { return token(yytext(),"INICIO",yyline,yycolumn);
            }
          // fall through
          case 119: break;
          case 58:
            { return token(yytext(),"TIPO_LOGICO",yyline,yycolumn);
            }
          // fall through
          case 120: break;
          case 59:
            { return token(yytext(),"REPITE",yyline,yycolumn);
            }
          // fall through
          case 121: break;
          case 60:
            { return token(yytext(),"TIPO_DECIMAL",yyline,yycolumn);
            }
          // fall through
          case 122: break;
          case 61:
            { return token(yytext(),"DEFAULT",yyline,yycolumn);
            }
          // fall through
          case 123: break;
          case 62:
            { return token(yytext(),"MOSTRAR",yyline,yycolumn);
            }
          // fall through
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
